name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches:
      - "*"
jobs:
  ci:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
      - run: |
          ./gradlew ci 
        env:
          LIBRARIAN_SONATYPE_USERNAME: ${{ secrets.LIBRARIAN_SONATYPE_USERNAME }}
          LIBRARIAN_SONATYPE_PASSWORD: ${{ secrets.LIBRARIAN_SONATYPE_PASSWORD }}
          LIBRARIAN_SIGNING_PRIVATE_KEY: ${{ secrets.LIBRARIAN_SIGNING_PRIVATE_KEY }}
          LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.LIBRARIAN_SIGNING_PRIVATE_KEY_PASSWORD }}
