name: prepare-release

on:
  workflow_dispatch:
    inputs:
      versionToRelease:
        description: 'The version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - run: |
          gh workflow trigger publish-release.yaml --ref v${{ inputs.versionToRelease }}
      - uses: gradleup/librarian/prepare-release@main
        with:
          versionToRelease: ${{ inputs.versionToRelease }}
    env:
      GH_TOKEN: ${{ github.token }}