name: tag-version

on:
  workflow_dispatch:
    inputs:
      versionToRelease:
        description: 'The version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: gradleup/librarian/tag-version@main
        with:
          versionToRelease: ${{ inputs.versionToRelease }}
